### ISSUE TITLE
Failed to resolve dependency

### ISSUE THREAD

**Issue by ianjuma** [zeeshanejaz/unirest-android#1]
Tried fetching dependencies using maven, below is the error. Is there an available jar file? The url seems invalid. 

``` bash
[ERROR] Failed to execute goal on project unirest-java: 
Could not resolve dependencies for project com.mashape.unirest:unirest-java:jar:1.4.5:
 Could not find artifact com.mashape.unirest:unirest-android:jar:1.0.1 in unirest-for-android 
(https://raw.github.com/zeeshanejaz/unirest-android/mvn-repo) -> [Help 1]
```

**Comment by apimatic** [comment]
Can you please use the updated fork from here: https://github.com/apimatic/unirest-android
The maven repo url for this is : https://raw.github.com/apimatic/unirest-android/mvn-repo
Also, can you tell me which tool are you using? Gradle / Eclipse ADT / Android Studio?

**Comment by ianjuma** [comment]
Android Studio, updated it - same error. Artifact doesn't seem to exist, could the README be updated as well

**Comment by ianjuma** [comment]
managed to resolve the issue

**Comment by BraulioRM** [comment]
how did you solve the problem at the end?
