### ISSUE TITLE
The maven repository doesn't work

### ISSUE THREAD

**Issue by timkoers** [zeeshanejaz/unirest-android#2]
The maven repository url isn't working anymore.
Got 400 error when accessing the url.

**Comment by apimatic** [comment]
Please see this link 
https://github.com/zeeshanejaz/unirest-android/tree/mvn-repo

**Comment by apimatic** [comment]
An updated version is available on
https://github.com/apimatic/unirest-android/tree/mvn-repo

**Comment by timkoers** [comment]
Thanks! Could you update the README.md file?

**Comment by apimatic** [comment]
Which url worked for you in Maven? I will add that to the README

**Comment by timkoers** [comment]
Haven’t tried something out yet.

Van: APIMATIC [mailto:notifications@github.com] 
Verzonden: zaterdag 20 juni 2015 15:04
Aan: zeeshanejaz/unirest-android
CC: timkoers
Onderwerp: Re: [unirest-android] The maven repository doesn't work (#2)

Which url worked for you in Maven? I will add that to the README
